/**
 * @tnc-trading/shared
 * Package de code partagé pour la plateforme TNC Trading
 */

// Types (main type definitions)
export * from './types/index.js';

// Validators (Zod schemas)
export * from './validators/index.js';

// Utilities
export * from './utils/index.js';

// Constants (excluding type re-exports)
export {
  APP_NAME,
  APP_VERSION,
  DEFAULT_COUNTRY,
  DEFAULT_CURRENCY,
  DEFAULT_LANGUAGE,
  GOLD_UNIT,
  GOLD_PRECISION,
  CASH_PRECISION,
  DEFAULT_SPREAD_BUY,
  DEFAULT_SPREAD_SELL,
  DEFAULT_USD_XOF_RATE,
  QUOTE_VALIDITY_SECONDS,
  PRICE_UPDATE_INTERVAL_SECONDS,
  KYC_LEVELS,
  KYC_STATUSES,
  KYC_LIMITS,
  KYC_DOCUMENT_TYPES,
  KYC_DOCUMENT_VALIDITY_YEARS,
  TRANSACTION_TYPES,
  TRANSACTION_STATUSES,
  MIN_BUY_GRAMS,
  MIN_SELL_GRAMS,
  MIN_DEPOSIT_XOF,
  MIN_WITHDRAWAL_XOF,
  STORAGE_FEE_ANNUAL_PERCENT,
  STORAGE_FEE_MONTHLY_PERCENT,
  WITHDRAWAL_FEE_MOBILE_MONEY_PERCENT,
  WITHDRAWAL_FEE_MOBILE_MONEY_MIN_XOF,
  WITHDRAWAL_FEE_BANK_PERCENT,
  WITHDRAWAL_FEE_BANK_MIN_XOF,
  PAYMENT_METHODS,
  DEPOSIT_METHODS,
  WITHDRAWAL_METHODS,
  WITHDRAWAL_DELAY,
  SESSION_TIMEOUT_MINUTES,
  REFRESH_TOKEN_DAYS,
  ACCESS_TOKEN_MINUTES,
  MAX_LOGIN_ATTEMPTS,
  LOCKOUT_DURATION_MINUTES,
  RATE_LIMIT_REQUESTS_PER_MINUTE,
  RATE_LIMIT_REQUESTS_PER_MINUTE_AUTH,
  PASSWORD_MIN_LENGTH,
  PASSWORD_REQUIRE_UPPERCASE,
  PASSWORD_REQUIRE_LOWERCASE,
  PASSWORD_REQUIRE_NUMBER,
  PASSWORD_REQUIRE_SPECIAL,
  TWO_FACTOR_CODE_LENGTH,
  TWO_FACTOR_CODE_VALIDITY_SECONDS,
  VERIFICATION_CODE_LENGTH,
  VERIFICATION_CODE_VALIDITY_MINUTES,
  STOCK_LOW_ALERT_PERCENT,
  POR_GENERATION_INTERVAL_DAYS,
  NOTIFICATION_TYPES,
  ADMIN_ROLES,
  ERROR_CODES,
  ERROR_MESSAGES,
  PHONE_COUNTRY_CODES,
  PHONE_REGEX_BF,
  DATE_FORMAT,
  DATETIME_FORMAT,
  TIME_FORMAT,
  TIMEZONE,
  SUPPORT_HOURS,
  SUPPORT_EMAIL,
  SUPPORT_PHONE,
} from './constants/index.js';
